# Cloudflare Workers Configuration for API
name = "e-commerce-369-api"
main = "functions/api/[[catchall]].js"
compatibility_date = "2024-12-01"

# KV namespaces for session storage and caching
[[kv_namespaces]]
binding = "SESSIONS"
id = "7cc8d27d9d334ad3b014328dc743c106"
preview_id = "7cc8d27d9d334ad3b014328dc743c106"

[[kv_namespaces]]
binding = "CACHE"
id = "35b31bbbdb6340eaaf79cbd9c10ec958"
preview_id = "35b31bbbdb6340eaaf79cbd9c10ec958"

# D1 Database for product data and user management
[[d1_databases]]
binding = "DB"
database_name = "brainsait-db"
database_id = "79e8eb7a-1ada-4016-b51c-2cc631405467"

# Environment variables
[vars]
NODE_ENV = "production"
JWT_SECRET = "your-jwt-secret-here"
MADA_API_KEY = "your-mada-api-key"
STC_PAY_API_KEY = "your-stc-pay-api-key"
STRIPE_SECRET_KEY = "your-stripe-secret-key"
PAYPAL_CLIENT_ID = "your-paypal-client-id"
PAYPAL_CLIENT_SECRET = "your-paypal-client-secret"
